Traceback (most recent call last):
  File "api.py", line 191, in <module>
    for p in list_prices('Rancor_Magic_2013.c1p256673.prod'):
  File "api.py", line 145, in list_prices
    r = requests.get(BASE + id, params=qs)
  File "/home/brodriguez/workspace/pymcm/local/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/brodriguez/workspace/pymcm/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/brodriguez/workspace/pymcm/local/lib/python2.7/site-packages/requests/sessions.py", line 354, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/brodriguez/workspace/pymcm/local/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/home/brodriguez/workspace/pymcm/local/lib/python2.7/site-packages/requests/adapters.py", line 246, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.magiccardmarket.eu', port=443): Max retries exceeded with url: /Rancor_Magic_2013.c1p256673.prod?idCategory=1&mainPage=showProduct&idProduct=256673 (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
